"""
The shell command of every TCoaRse step, in one place.

Each step of the pipeline exists twice: as a block of its own, wired by hand in
a flow, and as one step of the "TCoaRse Pipeline" block, which concatenates all
of them into a single job. Both build the same command, so it is defined here
once and called from both.

The builders take the paths and the settings explicitly rather than reading
them off the block, because the two callers resolve them differently: a
standalone block takes them from its inputs, while the pipeline block derives
them from the output prefix of the previous step. What they do read off the
block is the TCoaRse installation itself -- the interpreter, the scripts folder
and the models -- which is the same either way.
"""

import os
import shlex
import typing

from HorusAPI import PluginBlock

from tcoarse_utils import (  # type: ignore
    potential_dir,
    pydock_dir,
    pydock_sif,
    python_exec,
    script_path,
)

PYDOCK_CONFIG_NAME = "pydock_config.yaml"
PYDOCK_OUTPUT_DIR = "pydock_output"
PYDOCK_STAGING_DIR = "pydock_staging"


def write_pydock_config(
    pdb_dir: str,
    sif: str,
    modules: typing.List[str],
    chunk_size: int,
) -> str:
    """
    Write the pyDock config.yaml in the run folder and return its name.
    """
    modules = modules or ["bindEy"]

    lines = [
        "# Generated by the Horus Immunoinformatics plugin",
        "input_dirs:",
        f'  - "{pdb_dir}"',
        f'output_dir: "{PYDOCK_OUTPUT_DIR}"',
        'batch: "batch"',
        f"complexes_per_chunk: {int(chunk_size)}",
        f'singularity_image: "{sif}"',
        "pydock_modules:",
    ]
    lines += [f'  - "{module}"' for module in modules]
    lines += [
        "keep_file_patterns:",
        '  - "*.ene"',
        "copy_pdbs_to_tmpdir: true",
        "suppress_stdout: true",
        "suppress_stderr: true",
        'chain_mapping_json: ""',
        'chain_mapping_key_mode: "exact"',
        "",
    ]

    with open(PYDOCK_CONFIG_NAME, "w", encoding="utf-8") as file:
        file.write("\n".join(lines))

    return PYDOCK_CONFIG_NAME


def parse_pydock_modules(raw: typing.Any) -> typing.List[str]:
    """
    The pyDock modules, one per line, as configured on the block or the page.
    """
    return [line.strip() for line in str(raw or "").splitlines() if line.strip()] or [
        "bindEy"
    ]


def copy_models_command(
    block: PluginBlock, af3_dir: str, pdb_dir: str, workers: int
) -> str:
    """
    Convert the AF3 predictions into merged PDB files.
    """
    return (
        f"{python_exec(block)} {shlex.quote(script_path(block, 'cp_models.py'))}"
        f" {shlex.quote(af3_dir)}"
        f" {pdb_dir}"
        f" --workers {workers}"
    )


def structure_metadata_command(
    block: PluginBlock, pdb_dir: str, metadata_csv: str
) -> str:
    """
    Build the metadata table out of the structures.
    """
    return (
        f"{python_exec(block)} {shlex.quote(script_path(block, 'metadata_from_str.py'))}"
        f" {pdb_dir}"
        f" -o {metadata_csv}"
    )


def contact_maps_command(
    block: PluginBlock,
    pdb_dir: str,
    cm_dir: str,
    chain_map: str,
    workers: int,
    not_experimental: bool,
) -> str:
    """
    Compute the contact maps of every model.
    """
    command = (
        f"{python_exec(block)} {shlex.quote(script_path(block, 'contact_maps.py'))}"
        f" -pdb {pdb_dir}"
        f" -out {cm_dir}"
        f" -cm {shlex.quote(str(chain_map))}"
        f" -workers {workers}"
    )

    if not_experimental:
        command += " -notexp"

    return command


def pydock_command(
    block: PluginBlock, config: str, tar_path: str, cpus: int
) -> str:
    """
    Run the pyDock scoring of every model, chunk by chunk.

    Several commands rather than one: the manifest, the chunks and the chain
    mapping are prepared first, then every chunk is scored, and the shards are
    finally packed into a single tar.
    """
    python = python_exec(block)
    driver = pydock_dir(block)

    return "\n".join(
        [
            # The step is several commands, so it aborts on the first failure
            # instead of carrying on and packing an incomplete archive. Setting
            # it again inside the pipeline script is harmless.
            "set -e",
            f"rm -rf {PYDOCK_OUTPUT_DIR} {PYDOCK_STAGING_DIR}",
            f"{python} {shlex.quote(os.path.join(driver, '01_make_manifest.py'))}"
            f" --config {config}",
            f"{python} {shlex.quote(os.path.join(driver, '02_make_chunks.py'))}"
            f" --config {config}",
            f"{python} {shlex.quote(os.path.join(driver, '03_validate_chain_mapping.py'))}"
            f" --config {config}",
            f"for chunk in {PYDOCK_OUTPUT_DIR}/chunks/chunk_*.tsv; do",
            '  chunk_id=$(basename "$chunk" .tsv)',
            "  chunk_id=${chunk_id#chunk_}",
            # Strip the leading zeros of chunk_000012 by hand. $((10#$chunk_id))
            # is a bashism and the job runs under sh (dash on Debian/Ubuntu),
            # which rejects the 10# base prefix; plain $((008)) is no good
            # either, as it would be read as an invalid octal number.
            '  while [ "${chunk_id#0}" != "$chunk_id" ]; do chunk_id=${chunk_id#0}; done',
            '  [ -n "$chunk_id" ] || chunk_id=0',
            f'  {python} {shlex.quote(os.path.join(driver, "worker_chunk.py"))}'
            f" --config {config}"
            ' --chunk "$chunk"'
            ' --chunk-id "$chunk_id"'
            f" --local-sif {shlex.quote(pydock_sif(block))}"
            f" --cpus {cpus}",
            "done",
            f"mkdir -p {PYDOCK_STAGING_DIR}",
            f"for shard in {PYDOCK_OUTPUT_DIR}/archives/shards/*/chunk_*.tar; do",
            f'  tar -xf "$shard" -C {PYDOCK_STAGING_DIR}',
            "done",
            f"tar -cf {tar_path} -C {PYDOCK_STAGING_DIR} .",
        ]
    )


def pairwise_dockq_command(
    block: PluginBlock, pdb_dir: str, dockq_csv: str, workers: int
) -> str:
    """
    Compute the pairwise DockQ of the models.
    """
    return (
        f"{python_exec(block)} {shlex.quote(script_path(block, 'pw_sim.py'))}"
        f" --folder {pdb_dir}"
        f" --output {dockq_csv}"
        f" --workers {workers}"
    )


def energetic_scorer_command(
    block: PluginBlock,
    pdb_dir: str,
    cm_dir: str,
    energies_csv: str,
    chain_map: str,
    threshold: int,
    workers: int,
    io_workers: int,
    not_experimental: bool,
) -> str:
    """
    Score the contacts of every model with the statistical potentials.
    """
    command = (
        f"{python_exec(block)} {shlex.quote(script_path(block, 'energetic_scorer.py'))}"
        f" -pdb {pdb_dir}"
        f" -cmd {cm_dir}"
        f" -pot {shlex.quote(potential_dir(block))}"
        f" -out {energies_csv}"
        f" -chains {shlex.quote(str(chain_map))}"
        f" -t {int(threshold)}"
        f" -w {workers}"
        f" -io {int(io_workers)}"
    )

    if not_experimental:
        command += " -notexp"

    return command


def merge_energies_command(
    block: PluginBlock,
    energies_csv: str,
    metadata_csv: str,
    pydock_tar: str,
    merged_csv: str,
    metrics_csv: typing.Optional[str] = None,
) -> str:
    """
    Build the feature table of the predictors.
    """
    command = (
        f"{python_exec(block)} {shlex.quote(script_path(block, 'merge_energies.py'))}"
        f" -tcoarse {energies_csv}"
        f" -metadata {metadata_csv}"
        f" -tar {pydock_tar}"
        f" -o {merged_csv}"
    )

    if metrics_csv:
        command += f" -metrics {metrics_csv}"

    return command


def predictor_tcoarse_command(
    block: PluginBlock, merged_csv: str, predictions: str, model: str
) -> str:
    """
    Score the models with the TCoaRse model.
    """
    return (
        f"{python_exec(block)} {shlex.quote(script_path(block, 'predictor_tcoarse.py'))}"
        f" -df {merged_csv}"
        f" -m {shlex.quote(str(model))}"
        f" -out {predictions}"
    )
