"""
pyDock binding energies of the TCR-pMHC models.

Port of the `pydock` process of tcoarse_prediction.nf. The Nextflow version
copied `pydock/config.yaml` and patched it with `sed` (against placeholders
that the shipped config no longer has) and only ever processed the first chunk.
Here the config is generated from scratch and every chunk is processed.
"""

import os
import shlex

from HorusAPI import PluginVariable, SlurmBlock, VariableTypes

from slurm_utils import BSC_JOB_VARIABLES  # type: ignore
from tcoarse_utils import (  # type: ignore
    TCOARSE_CATEGORY,
    TCOARSE_COLOR,
    output_prefix,
    ensure_produced,
    finish,
    job_cpus,
    launch,
    pydock_dir,
    pydock_sif,
    python_exec,
    required_input,
    stage,
    variable_or,
)

# ==========================#
# Inputs
# ==========================#
pdb_dir_variable = PluginVariable(
    id="pdb_dir",
    name="PDB folder",
    description="Folder with the merged PDB models.",
    type=VariableTypes.FOLDER,
    required=True,
)

# ==========================#
# Outputs
# ==========================#
pydock_tar_output = PluginVariable(
    id="pydock_tar",
    name="pyDock energies",
    description="TAR archive with the .ene files of every model.",
    type=VariableTypes.FILE,
    allowedValues=["tar"],
)

# ==========================#
# Other variables
# ==========================#
chunk_size_variable = PluginVariable(
    id="complexes_per_chunk",
    name="Complexes per chunk",
    description="Number of complexes processed by each pyDock chunk.",
    type=VariableTypes.INTEGER,
    defaultValue=5000,
)

modules_variable = PluginVariable(
    id="pydock_modules",
    name="pyDock modules",
    description="pyDock modules to run, one per line.",
    type=VariableTypes.TEXT_AREA,
    defaultValue="bindEy",
)

CONFIG_NAME = "pydock_config.yaml"
OUTPUT_DIR = "pydock_output"
STAGING_DIR = "pydock_staging"


def _write_config(block: SlurmBlock, pdb_dir: str) -> str:
    """
    Write the pyDock config.yaml in the run folder and return its name.
    """

    modules = [
        line.strip()
        for line in str(variable_or(block, modules_variable, "bindEy")).splitlines()
        if line.strip()
    ] or ["bindEy"]

    lines = [
        "# Generated by the Horus Immunoinformatics plugin",
        "input_dirs:",
        f'  - "{pdb_dir}"',
        f'output_dir: "{OUTPUT_DIR}"',
        'batch: "batch"',
        f"complexes_per_chunk: {int(variable_or(block, chunk_size_variable, 5000))}",
        f'singularity_image: "{pydock_sif(block)}"',
        "pydock_modules:",
    ]
    lines += [f'  - "{module}"' for module in modules]
    lines += [
        "keep_file_patterns:",
        '  - "*.ene"',
        "copy_pdbs_to_tmpdir: true",
        "suppress_stdout: true",
        "suppress_stderr: true",
        'chain_mapping_json: ""',
        'chain_mapping_key_mode: "exact"',
        "",
    ]

    with open(CONFIG_NAME, "w", encoding="utf-8") as file:
        file.write("\n".join(lines))

    return CONFIG_NAME


def initial_pydock(block: SlurmBlock):
    """
    Run the pyDock scoring of every model.
    """

    pdb_dir = stage(required_input(block, pdb_dir_variable))
    prefix = output_prefix(block)

    cpus = job_cpus(block)
    tar_path = f"{prefix}_pydock_ene.tar"

    config = _write_config(block, pdb_dir)

    python = python_exec(block)
    driver = pydock_dir(block)
    sif = pydock_sif(block)

    command = "\n".join(
        [
            "set -e",
            f"rm -rf {OUTPUT_DIR} {STAGING_DIR}",
            f"{python} {shlex.quote(os.path.join(driver, '01_make_manifest.py'))} --config {config}",
            f"{python} {shlex.quote(os.path.join(driver, '02_make_chunks.py'))} --config {config}",
            f"{python} {shlex.quote(os.path.join(driver, '03_validate_chain_mapping.py'))} --config {config}",
            # The Nextflow pipeline hardcoded chunk_000000; process every chunk
            f"for chunk in {OUTPUT_DIR}/chunks/chunk_*.tsv; do",
            '  chunk_id=$(basename "$chunk" .tsv)',
            "  chunk_id=${chunk_id#chunk_}",
            "  chunk_id=$((10#$chunk_id))",
            f'  {python} {shlex.quote(os.path.join(driver, "worker_chunk.py"))}'
            f" --config {config}"
            ' --chunk "$chunk"'
            ' --chunk-id "$chunk_id"'
            f" --local-sif {shlex.quote(sif)}"
            f" --cpus {cpus}",
            "done",
            f"mkdir -p {STAGING_DIR}",
            f"for shard in {OUTPUT_DIR}/archives/shards/*/chunk_*.tar; do",
            f'  tar -xf "$shard" -C {STAGING_DIR}',
            "done",
            f"tar -cf {tar_path} -C {STAGING_DIR} .",
        ]
    )

    block.extraData["pydock_tar"] = tar_path

    print("Scoring the models with pyDock")

    launch(block, command, upload=[pdb_dir, config])


def final_pydock(block: SlurmBlock):
    """
    Publish the archive with the pyDock energies.
    """

    finish(block)

    tar_path = ensure_produced(block.extraData["pydock_tar"], "The pyDock archive")

    print(f"pyDock energies written to '{tar_path}'")

    block.setOutput(pydock_tar_output.id, tar_path)


pydockEnergiesBlock = SlurmBlock(
    id="tcoarse_pydock",
    name="pyDock Energies",
    description=(
        "Score every TCR-pMHC model with pyDock (inside its Singularity "
        "container) and pack the resulting .ene files into a single archive."
    ),
    initialAction=initial_pydock,
    finalAction=final_pydock,
    inputs=[pdb_dir_variable],
    variables=BSC_JOB_VARIABLES + [chunk_size_variable, modules_variable],
    outputs=[pydock_tar_output],
    category=TCOARSE_CATEGORY,
    color=TCOARSE_COLOR,
)
